// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO0rD9B5JzjD0LG844qE2JqdztScBGKG0',
    appId: '1:821514924725:web:73c8aea13c1ed310db04fc',
    messagingSenderId: '821514924725',
    projectId: 'flutter-ai-playground-2f1dd',
    authDomain: 'flutter-ai-playground-2f1dd.firebaseapp.com',
    storageBucket: 'flutter-ai-playground-2f1dd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfpIgArIUs-eR35A81PCKaSZJ6wu3M14A',
    appId: '1:821514924725:android:eda331a39d87ce12db04fc',
    messagingSenderId: '821514924725',
    projectId: 'flutter-ai-playground-2f1dd',
    storageBucket: 'flutter-ai-playground-2f1dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1MKmj5OJLMbCb95UOv1_UgcNcQ6IRxp8',
    appId: '1:821514924725:ios:fe53835b0d4bfa39db04fc',
    messagingSenderId: '821514924725',
    projectId: 'flutter-ai-playground-2f1dd',
    storageBucket: 'flutter-ai-playground-2f1dd.firebasestorage.app',
    iosBundleId: 'com.example.ktpl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1MKmj5OJLMbCb95UOv1_UgcNcQ6IRxp8',
    appId: '1:821514924725:ios:fe53835b0d4bfa39db04fc',
    messagingSenderId: '821514924725',
    projectId: 'flutter-ai-playground-2f1dd',
    storageBucket: 'flutter-ai-playground-2f1dd.firebasestorage.app',
    iosBundleId: 'com.example.ktpl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO0rD9B5JzjD0LG844qE2JqdztScBGKG0',
    appId: '1:821514924725:web:25925fa847781627db04fc',
    messagingSenderId: '821514924725',
    projectId: 'flutter-ai-playground-2f1dd',
    authDomain: 'flutter-ai-playground-2f1dd.firebaseapp.com',
    storageBucket: 'flutter-ai-playground-2f1dd.firebasestorage.app',
  );

}